import { i18n } from "./data";

type TranslationParams = Record<string, unknown> & {
  _context?: string;
  _comment?: string;
};

const fixedTranslations: Record<string, string> = {
  "General": "概况",
  "Material": "材质",
  "Volume": "体积",
  "Weight": "重量",
  "Length": "长度",
  "Compatible Magazines": "兼容弹匣",
  "Flags": "属性标签",
  "Usage": "用途",
  "Tool": "工具",
  "Tools": "工具",
  "Melee": "近战",
  "Ammo": "弹药",
  "Ammunition": "弹药",
  "Charges Per Use": "每次消耗充能",
  "Raw JSON": "原始 JSON",
  "Error": "错误",
  "Unknown object: {id}": "未知对象：{id}",
  "There was a problem displaying this page. Not all versions of Cataclysm are supported by the Guide currently. Try selecting a different build.":
    "显示此页面时出现了问题。当前指南可能无法完整兼容这条数据，请返回上一页或展开原始 JSON 查看。",
  "No results.": "没有结果。",
  "location": "地点",
  "({n} variants)": "（{n} 个变体）",
  "obsolete": "已废弃",
  "Loading...": "加载中……",
  "See all {n}...": "查看全部 {n} 项……",
  "Reveal Spoilers": "显示剧透内容",
  "Spoiler Warning": "剧透警告",
  "Yes": "是",
  "No": "否",
  "none": "无",
  "nothing": "无",
  "default": "默认",
  "Default": "默认",
  "Name": "名称",
  "Description": "说明",
  "Type": "类型",
  "Category": "分类",
  "Item": "物品",
  "Items": "物品",
  "Monster": "怪物",
  "Monsters": "怪物",
  "Furniture": "家具",
  "Terrain": "地形",
  "Vehicle Part": "载具部件",
  "Vehicle Parts": "载具部件",
  "Vehicle": "载具",
  "Vehicles": "载具",
  "Mutation": "变异",
  "Mutations": "变异",
  "Mutation Category": "变异类别",
  "Mutation Type": "变异类型",
  "Martial Art": "武术",
  "Martial Arts": "武术",
  "Proficiency": "专长",
  "Proficiencies": "专长",
  "Skill": "技能",
  "Skills Used": "使用技能",
  "Skills Required": "所需技能",
  "Book": "书籍",
  "Books": "书籍",
  "Armor": "护甲",
  "Bionic": "仿生器官",
  "Bionics": "仿生器官",
  "Flag": "标记",
  "Fault": "故障",
  "Vitamin": "维生素",
  "Vitamins": "维生素",
  "Weapon Category": "武器类别",
  "Construction": "建造",
  "Constructions": "建造",
  "Recipe": "配方",
  "Recipes": "配方",
  "Components": "材料",
  "Requirements": "需求",
  "Required:": "必需：",
  "Difficulty": "难度",
  "Time": "时间",
  "Duration": "持续时间",
  "Damage": "伤害",
  "Base Damage": "基础伤害",
  "Armor Penetration": "穿甲",
  "Range": "射程",
  "Dispersion": "散布",
  "Recoil": "后坐力",
  "Capacity": "容量",
  "Count": "数量",
  "Chance": "概率",
  "Min": "最小",
  "Max": "最大",
  "Level {level}": "等级 {level}",
  "Strength": "力量",
  "Dexterity": "敏捷",
  "Intelligence": "智力",
  "Perception": "感知",
  "Strength Required": "力量需求",
  "Moves Per Attack": "每次攻击耗时",
  "To Hit": "命中",
  "Bash": "钝击",
  "Cut": "斩击",
  "Stab": "刺击",
  "Protection": "防护",
  "Coverage": "覆盖率",
  "Encumbrance": "累赘",
  "Warmth": "保暖",
  "Breathability": "透气性",
  "Layer": "层级",
  "Close to skin": "贴身",
  "Outer": "外层",
  "Rigid": "刚性",
  "Sided": "分左右",
  "Conductive": "导电",
  "Edible": "可食用",
  "Calories": "热量",
  "Enjoyability": "享受度",
  "Health": "健康值",
  "Morale": "士气",
  "Spoils In": "腐坏时间",
  "Tools Required": "所需工具",
  "Qualities": "工具功能",
  "Qualities (Charged)": "充能时工具功能",
  "Quality": "工具功能",
  "Provided By": "提供来源",
  "Used By": "用途",
  "Used In Construction": "用于建造",
  "Used to Repair": "用于修理",
  "Repaired With": "修理工具",
  "Component Of": "可用于制作",
  "Obtaining": "获取方式",
  "Dropped By": "掉落来源",
  "Found In": "出现位置",
  "Grown From": "种植来源",
  "Harvested From": "采集来源",
  "Disassemble": "拆解",
  "Disassembles Into": "拆解产物",
  "Salvage": "切割回收",
  "Salvaged Into": "回收产物",
  "Deconstruct": "拆除",
  "Transforms Into": "转化为",
  "Transformed From": "来源于",
  "Turns Into": "变为",
  "Fuel": "燃料",
  "Fuel Capacity": "燃料容量",
  "Power": "功率",
  "Power Draw": "耗电",
  "Electric Power": "电力",
  "Install": "安装",
  "Remove": "拆除",
  "Reload Time": "装填时间",
  "Reload Noise Volume": "装填噪音",
  "Pockets": "口袋",
  "Volume Capacity": "体积容量",
  "Weight Capacity": "重量容量",
  "Max Item Length": "最大物品长度",
  "Min Item Volume": "最小物品体积",
  "Max Items": "最大物品数",
  "Max Stacks": "最大堆叠数",
  "Item Restriction": "限定物品",
  "Ammo Restriction": "限定弹药",
  "Flag Restriction": "限定标志",
  "Compatible Items": "兼容物品",
  "Effects": "效果",
  "Effect Name": "效果名称",
  "Special Attacks": "特殊攻击",
  "Species": "物种",
  "Default Faction": "默认阵营",
  "Aggression": "攻击性",
  "Vision Range": "视野范围",
  "Speed": "速度",
  "HP": "生命值",
  "Dodge": "闪避",
  "Attack": "攻击",
  "Techniques": "武技",
  "Technique": "武技",
  "Prerequisites": "前置条件",
  "Conflicts With Mutations": "冲突变异",
  "Cancels": "取消",
  "Leads To": "后续变异",
  "Threshold Mutation": "阈值变异",
  "Purifiable": "可净化",
  "Points": "点数",
  "Visibility": "可见性",
  "Body Type": "体型",
  "Body Part": "身体部位",
  "Occupied Body Parts": "占用身体部位",
  "Properties": "属性",
  "Result": "结果",
  "Byproducts": "副产物",
  "Byproduct": "副产物",
  "Possible Recipes": "可能配方",
  "Practice Recipes": "练习配方",
  "Autolearn": "自动学会",
  "Primary Skill": "主要技能",
  "Other Skills": "其他技能",
  "Read Time": "阅读时间",
  "Chapters": "章节",
  "Difficulty to Learn": "学习难度",
  "Time to Learn": "学习时间",
  "Written In": "记载于",
  "Noise": "噪音",
  "Loudness": "响度",
  "Light": "光照",
  "Fun": "乐趣",
  "Fear Triggers": "恐惧触发条件",
  "Anger Triggers": "愤怒触发条件",
  "Placate Triggers": "安抚触发条件",
  "Activation Cost": "启用消耗",
  "Trigger Cost": "触发消耗",
  "Charge Time": "充能时间",
  "Turns Per Charge": "每次充能持续回合",
  "No items use this ammo.": "没有物品使用这种弹药。",
  "There are no martial arts that use this weapon category.": "没有武术使用这个武器类别。",
  "There are no weapons in this category.": "这个类别中没有武器。",
  "This location's appearance is dynamically generated.": "这个地点的外观由游戏动态生成。",
  "This recipe is not learnable. It may be used by NPCs or for debugging purposes.":
    "这个配方无法由玩家学习，可能仅供 NPC 或调试使用。",
  "Repair time and requirements are lower for parts that are less damaged.":
    "损坏较轻的部件需要更少的修理时间和材料。",
  "Gear worn on this body part must be large enough to accommodate abnormally large mutated anatomy.":
    "穿戴在这个身体部位的装备必须足够宽大，才能容纳异常增大的变异肢体。",
  "You can't have two mutations that share a type.": "不能同时拥有两个相同类型的变异。",
  "Behavior": "行为",
  "Upgrades Into": "进化为",
  "Drops": "掉落物",
  "Avg. Count": "平均数量",
  "Butchering Results": "屠宰产物",
  "with a half-life of {days} days": "，半衰期为 {days} 天",
  "night": "夜间",
  "Day": "天",
  "days": "天",
  "Faction": "阵营",
  "Status": "状态",
  "Source": "来源",
  "Search": "搜索",
  "Search...": "搜索……",
  "Search……": "搜索……",
  "Guide data failed to load": "指南数据加载失败",
  "Reload": "重新加载",
  "Mod data": "模组数据",
  "objects": "个对象",
  "required": "必需",
  "Version:": "版本：",
  "Behavioral": "行为",
  "Attack Cost": "攻击耗时",
  "Upgrade Into": "进化为",
  "Drop": "掉落物",
  "Average Count": "平均数量",
  "Butchering": "屠宰",
  "Tool Quality": "工具功能",
  "Tool Qualities": "工具功能",
};

const typeTranslations: Record<string, string> = {
  ITEM: "物品",
  AMMO: "弹药",
  ARMOR: "护甲",
  BATTERY: "电池",
  BIONIC_ITEM: "仿生器官",
  BOOK: "书籍",
  COMESTIBLE: "食物与药品",
  ENGINE: "引擎",
  GENERIC: "杂项物品",
  GUN: "枪械",
  GUNMOD: "枪械配件",
  MAGAZINE: "弹匣",
  PET_ARMOR: "宠物护甲",
  TOOL: "工具",
  TOOLMOD: "工具配件",
  TOOL_ARMOR: "可穿戴工具",
  WHEEL: "车轮",
  item: "物品",
  monster: "怪物",
  furniture: "家具",
  terrain: "地形",
  vehicle_part: "载具部件",
  tool_quality: "功能",
  mutation: "变异",
  mutation_category: "变异类别",
  mutation_type: "变异类型",
  martial_art: "武术",
  json_flag: "标记",
  monster_flag: "怪物标记",
  achievement: "成就",
  conduct: "守则",
  proficiency: "专长",
  skill: "技能",
  vehicle: "载具",
  overmap_special: "地点",
  city_building: "地点",
  bionic: "仿生器官",
  fault: "故障",
  vitamin: "维生素",
  material: "材质",
  ammunition_type: "弹药类型",
  addiction_type: "成瘾类型",
  weapon_category: "武器类别",
  construction_group: "建造类别",
  item_action: "物品动作",
  technique: "武技",
};

export function cleanDisplayName(value: unknown): string {
  return String(value ?? "")
    .replace(/<color_[^>]+>/gi, "")
    .replace(/<\/color>/gi, "")
    .trim();
}

export function t(source: string, params: TranslationParams = {}): string {
  const { _context: _ignoredContext, _comment: _ignoredComment, ...values } = params;
  let translated = source;
  try {
    const fromGame = i18n.gettext(source);
    if (fromGame && fromGame !== source) translated = fromGame;
  } catch {
    // 翻译数据尚未加载时使用内置中文表。
  }
  if (translated === source) translated = fixedTranslations[source] ?? source;
  for (const [key, value] of Object.entries(values)) {
    translated = translated.replaceAll(`{${key}}`, String(value));
  }
  return translated;
}

export function guideTypeName(type: string): string {
  return typeTranslations[type] ?? t(type.replace(/_/g, " "));
}
